/*!
 * tableaux.js
 */

'use strict';
let tableaux = {
   tabNom: [ 
               'Martin',
               'Marchand',
               'Trudeau',
               'Lafontaine',
               'Gravel',
               'Huberdeau',
               'Massé',
               'St-Pierre',
               'Dandurand',
               'Hamel',
               'Larose',
               'Ambroise',
               'Kuvel',
               'Lamarre',
               'Sorel',
               'Frapier',
               'Archer',
               'Dejoie',
               'Moïse',
               'Fortin',
               'Stien',
               'Gagnon',
               'Chédiac',
               'Roy',
               'Gagner',
               'Larue',
               'Lafortune',
               'Roffi',
               'Cartier',
               'Maisonneuve',
               'Levesque',
               'Talon',
               'Bellemarre',
               'Mercier'
               ],

tabCourriel: [
                  'hotmail.com',
                  'vedeotron.com',
                  'gmail.com',
                  'yahoo.com',
                  'cmaisonneuve.qc.ca',
                  'webfaction.com',
                  'cvsyc.com',
                  'bell.ca',
                  'umontreal.ca',
                  'skillscanada.ca',
                  'inforoutefpt.com'
                  ],

ville: [
            'Montréal',
            'Québec',
            'Saskatshewan',
            'Calgary',
            'Edmonton',
            'Laval',
            'Ottawa',
            'Gatineau',
            'Gaspé',
            'Hudson',
            'New York'
            ],

tabPrenom: [
                  'Luc',
                  'Éric',
                  'François',
                  'Lyne',
                  'carolle',
                  'Sylvie',
                  'Renée',
                  'Mathieu',
                  'Eddy',
                  'Jean',
                  'Paul',
                  'Gustave',
                  'Rose-Lyne',
                  'Rose-Lise',
                  'Rose',
                  'Xavier',
                  'Olivier',
                  'Michel',
                  'Jean-François',
                  'Bob',
                  'Gil',
                  'Martin',
                  'Pierre',
                  'Maxime',
                  'Léo',
                  'Léo-Paul',
                  'Paul',
                  'Alix',
                  'Alixe',
                  'Chantal',
                  'Christelle',
                  'Katy',
                  'Johanne',
                  'Béatrice',
                  'Noémie',
                  'Coralie',
                  'Pénéloppe',
                  'Charlotte'
                    ]
}

module.exports.tabNom = tableaux;


/*let tabNom = [ 
               'Martin',
               'Marchand',
               'Trudeau',
               'Lafontaine',
               'Gravel',
               'Huberdeau',
               'Massé',
               'St-Pierre',
               'Dandurand',
               'Hamel',
               'Larose',
               'Ambroise',
               'Kuvel',
               'Lamarre',
               'Sorel',
               'Frapier',
               'Archer',
               'Dejoie',
               'Moïse',
               'Fortin',
               'Stien',
               'Gagnon',
               'Chédiac',
               'Roy',
               'Gagner',
               'Larue',
               'Lafortune',
               'Roffi',
               'Cartier',
               'Maisonneuve',
               'Levesque',
               'Talon',
               'Bellemarre',
               'Mercier'
               ]

let tabCourriel = [
                  'hotmail.com',
                  'vedeotron.com',
                  'gmail.com',
                  'yahoo.com',
                  'cmaisonneuve.qc.ca',
                  'webfaction.com',
                  'cvsyc.com',
                  'bell.ca',
                  'umontreal.ca',
                  'skillscanada.ca',
                  'inforoutefpt.com']

let ville = [
            'Montréal',
            'Québec',
            'Saskatshewan',
            'Calgary',
            'Edmonton',
            'Laval',
            'Ottawa',
            'Gatineau',
            'Gaspé',
            'Hudson',
            'New York'
            ]

let tabPrenom = [
                  'Luc',
                  'Éric',
                  'François',
                  'Lyne',
                  'carolle',
                  'Sylvie',
                  'Renée',
                  'Mathieu',
                  'Eddy',
                  'Jean',
                  'Paul',
                  'Gustave',
                  'Rose-Lyne',
                  'Rose-Lise',
                  'Rose',
                  'Xavier',
                  'Olivier',
                  'Michel',
                  'Jean-François',
                  'Bob',
                  'Gil',
                  'Martin',
                  'Pierre',
                  'Maxime',
                  'Léo',
                  'Léo-Paul',
                  'Paul',
                  'Alix',
                  'Alixe',
                  'Chantal',
                  'Christelle',
                  'Katy',
                  'Johanne',
                  'Béatrice',
                  'Noémie',
                  'Coralie',
                  'Pénéloppe',
                  'Charlotte'
                    ]

module.exports.tabNom = tabNom;
module.exports.tabPrenom = tabPrenom;*/
